name: Website NPM Build
on: [create, push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Volans Website Build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          check-latest: true
      - name: install packages
        run: npm ci
      - name: Build website
        run: npm run build